name: OnPRLabeled
run-name: "${{github.workflow}}-${{github.event.label.name}}-${{github.event.number}}"
on:
  pull_request_target:
    types: [ labeled ]

concurrency:
  group: ${{github.workflow}}-${{github.event.label.name}}-${{github.event.number}}
  cancel-in-progress: true

env:
  PR_NUMBER:          ${{ github.event.number }}
  MODULES_BLACKLIST:  ${{ vars.GATETEST_MODULES_BLACKLIST }} ${{ vars.UNITTEST_MODULES_BLACKLIST }}

jobs:
  AsteriskCherryPickTest:
    name: AsteriskCherryPickTest
    if: ${{ github.event.label.name == vars.CHERRY_PICK_TEST_LABEL }}
    uses: asterisk/asterisk-ci-actions/.github/workflows/AsteriskCherryPickTest.yml@main
    secrets:
      ASTERISKTEAM_PAT: ${{ secrets.ASTERISKTEAM_PAT }}

  AsteriskRecheckPR:
    name: AsteriskRecheckPR
    if: ${{ github.event.label.name == vars.RECHECKPR_LABEL }}
    uses: asterisk/asterisk-ci-actions/.github/workflows/AsteriskRecheckPR.yml@main
    secrets:
      ASTERISKTEAM_PAT: ${{ secrets.ASTERISKTEAM_PAT }}

